name: helm2cattle
apiVersion: v1
home: https://codejam.ninja
icon: ''
version: 0.0.1
appVersion: latest
description: 'pass the cattle app id down to resources deployed by the helm operator'
keywords:
  - silicon
  - operator
  - database
  - key
  - cache
  - db
sources:
  - https://github.com/codejamninja/helm2cattle
maintainers:
  - name: 'Jam Risser'
    email: jam@codejam.ninja
