images:
  helm2cattle:
    repository: codejamninja/operators_helm2cattle
    tag: 0.0.2

config:
  clusterProvider: infrastructure
  imagePullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  helm2cattle:
    baseUrl: ''
    hostname: ''
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
